name: CI/CD BACKEND-DEMO

on:
  push:
    branches: ['master']
env:
  IMAGE_NAME: 'ghcr.io/segundocarmen/backend-demo'
  IMAGE_TAG: 'latest'
  CONTAINER_NAME: '/backend-demo'
jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag $(echo $IMAGE_NAME):$(echo $IMAGE_TAG)
      - name: Push the Docker image
        run: |
          docker login ghcr.io -u segundocarmen -p ${{ secrets.GH_TOKEN }}
          docker push $(echo $IMAGE_NAME):$(echo $IMAGE_TAG)

  deploy:
    needs: build_and_push_image
    runs-on: ubuntu-latest
    steps:
      - name: SSH Login server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd /APPLICATION
            sh main.sh
